import { type Abbreviations, type Player, PlayerType } from './definitions';

export const abbreviations: Abbreviations = {
  number: '#',
  name: 'Name',
  birthdate: 'Born',
  type: 'Type',
  position: 'POS',
  games_played: 'GP',
  goals: 'G',
  assists: 'A',
  points: 'P',
  wins: 'W',
  losses: 'L',
  overtime_losses: 'OT',
  save_percentage: 'SV%',
  goals_against_average: 'GAA',
};

export const rostersData: Record<string, Player[]> = {
  USA: [
    {
      type: PlayerType.Forward,
      number: 7,
      name: 'B. Tkachuk',
      birthdate: 937429200000,
      position: 'L',
      games_played: 56,
      goals: 21,
      assists: 23,
      points: 44,
    },
    {
      type: PlayerType.Forward,
      number: 9,
      name: 'J. Eichel',
      birthdate: 846453600000,
      position: 'C',
      games_played: 55,
      goals: 19,
      assists: 50,
      points: 69,
    },
    {
      type: PlayerType.Forward,
      number: 10,
      name: 'J.T. Miller',
      birthdate: 732060000000,
      position: 'C',
      games_played: 45,
      goals: 11,
      assists: 28,
      points: 39,
    },
    {
      type: PlayerType.Defensemen,
      number: 8,
      name: 'Z. Werenski',
      birthdate: 869259600000,
      games_played: 55,
      goals: 17,
      assists: 42,
      points: 59,
    },
    {
      type: PlayerType.Defensemen,
      number: 14,
      name: 'B. Faber',
      birthdate: 1029963600000,
      games_played: 52,
      goals: 6,
      assists: 16,
      points: 22,
    },
    {
      type: PlayerType.Defensemen,
      number: 15,
      name: 'N. Hanifin',
      birthdate: 854143200000,
      games_played: 56,
      goals: 6,
      assists: 17,
      points: 23,
    },
    {
      type: PlayerType.Goalie,
      number: 30,
      name: 'J. Oettinger',
      birthdate: 913932000000,
      games_played: 40,
      wins: 26,
      losses: 12,
      overtime_losses: 2,
      save_percentage: 0.911,
      goals_against_average: 2.35,
    },
    {
      type: PlayerType.Goalie,
      number: 37,
      name: 'C. Hellebuyck',
      birthdate: 737758800000,
      games_played: 43,
      wins: 34,
      losses: 7,
      overtime_losses: 2,
      save_percentage: 0.925,
      goals_against_average: 2.06,
    },
    {
      type: PlayerType.Goalie,
      number: 1,
      name: 'J. Swayman',
      birthdate: 911858400000,
      games_played: 40,
      wins: 18,
      losses: 18,
      overtime_losses: 4,
      save_percentage: 0.898,
      goals_against_average: 2.98,
    },
  ],
  Canada: [
    {
      type: PlayerType.Forward,
      number: 9,
      name: 'S. Bennett',
      birthdate: 835218000000,
      position: 'C',
      games_played: 55,
      goals: 18,
      assists: 17,
      points: 35,
    },
    {
      type: PlayerType.Forward,
      number: 11,
      name: 'T. Konecny',
      birthdate: 858031200000,
      position: 'R',
      games_played: 57,
      goals: 22,
      assists: 39,
      points: 61,
    },
    {
      type: PlayerType.Forward,
      number: 13,
      name: 'S. Reinhart',
      birthdate: 815608800000,
      position: 'C',
      games_played: 57,
      goals: 31,
      assists: 31,
      points: 62,
    },
    {
      type: PlayerType.Forward,
      number: 16,
      name: 'M. Marner',
      birthdate: 862779600000,
      position: 'R',
      games_played: 54,
      goals: 16,
      assists: 55,
      points: 71,
    },
    {
      type: PlayerType.Forward,
      number: 21,
      name: 'B. Point',
      birthdate: 826668000000,
      position: 'C',
      games_played: 50,
      goals: 31,
      assists: 27,
      points: 58,
    },
    {
      type: PlayerType.Forward,
      number: 24,
      name: 'S. Jarvis',
      birthdate: 1012514400000,
      position: 'C',
      games_played: 49,
      goals: 22,
      assists: 23,
      points: 45,
    },
    {
      type: PlayerType.Forward,
      number: 29,
      name: 'N. MacKinnon',
      birthdate: 809902800000,
      position: 'C',
      games_played: 57,
      goals: 21,
      assists: 66,
      points: 87,
    },
    {
      type: PlayerType.Forward,
      number: 38,
      name: 'B. Hagel',
      birthdate: 904165200000,
      position: 'L',
      games_played: 55,
      goals: 26,
      assists: 36,
      points: 62,
    },
    {
      type: PlayerType.Forward,
      number: 61,
      name: 'M. Stone',
      birthdate: 705704400000,
      position: 'R',
      games_played: 42,
      goals: 14,
      assists: 35,
      points: 49,
    },
    {
      type: PlayerType.Forward,
      number: 63,
      name: 'B. Marchand',
      birthdate: 579297600000,
      position: 'L',
      games_played: 57,
      goals: 20,
      assists: 24,
      points: 44,
    },
    {
      type: PlayerType.Forward,
      number: 71,
      name: 'A. Cirelli',
      birthdate: 868914000000,
      position: 'C',
      games_played: 53,
      goals: 20,
      assists: 22,
      points: 42,
    },
    {
      type: PlayerType.Forward,
      number: 87,
      name: 'S. Crosby',
      birthdate: 555278400000,
      position: 'C',
      games_played: 55,
      goals: 17,
      assists: 41,
      points: 58,
    },
    {
      type: PlayerType.Forward,
      number: 97,
      name: 'C. McDavid',
      birthdate: 853106400000,
      position: 'C',
      games_played: 49,
      goals: 22,
      assists: 49,
      points: 71,
    },
    {
      type: PlayerType.Defensemen,
      number: 5,
      name: 'D. Toews',
      birthdate: 761781600000,
      games_played: 53,
      goals: 6,
      assists: 21,
      points: 27,
    },
    {
      type: PlayerType.Defensemen,
      number: 6,
      name: 'T. Sanheim',
      birthdate: 828050400000,
      games_played: 57,
      goals: 6,
      assists: 21,
      points: 27,
    },
    {
      type: PlayerType.Defensemen,
      number: 8,
      name: 'C. Makar',
      birthdate: 909698400000,
      games_played: 57,
      goals: 22,
      assists: 41,
      points: 63,
    },
    {
      type: PlayerType.Defensemen,
      number: 27,
      name: 'S. Theodore',
      birthdate: 807397200000,
      games_played: 55,
      goals: 7,
      assists: 41,
      points: 48,
    },
    {
      type: PlayerType.Defensemen,
      number: 44,
      name: 'J. Morrissey',
      birthdate: 796338000000,
      games_played: 56,
      goals: 7,
      assists: 39,
      points: 46,
    },
    {
      type: PlayerType.Defensemen,
      number: 55,
      name: 'C. Parayko',
      birthdate: 737154000000,
      games_played: 55,
      goals: 12,
      assists: 17,
      points: 29,
    },
    {
      type: PlayerType.Defensemen,
      number: 55,
      name: 'D. Doughty',
      birthdate: 629067600000,
      games_played: 6,
      goals: 0,
      assists: 1,
      points: 1,
    },
    {
      type: PlayerType.Goalie,
      number: 50,
      name: 'J. Binnington',
      birthdate: 742338000000,
      games_played: 39,
      wins: 15,
      losses: 19,
      overtime_losses: 4,
      save_percentage: 0.897,
      goals_against_average: 2.89,
    },
    {
      type: PlayerType.Goalie,
      number: 33,
      name: 'A. Hill',
      birthdate: 831762000000,
      games_played: 34,
      wins: 20,
      losses: 10,
      overtime_losses: 4,
      save_percentage: 0.9,
      goals_against_average: 2.64,
    },
    {
      type: PlayerType.Goalie,
      number: 35,
      name: 'S. Montembeault',
      birthdate: 846626400000,
      games_played: 42,
      wins: 18,
      losses: 21,
      overtime_losses: 3,
      save_percentage: 0.897,
      goals_against_average: 3.0,
    },
  ],
};
